### ISSUE TITLE
下列对SQL注入防护措施中的转码描述正确的是(2分)   A. 转码仅对拼接SQL语句中，单引号或双引号限制的字段生效

### ISSUE THREAD

**Issue by waylau** [waylau/java-trusted-coding-exam#68]
下列对SQL注入防护措施中的转码描述正确的是(2分)

 A. 转码仅对拼接SQL语句中，单引号或双引号限制的字段生效
 B. 转码对表名、字段等不乱用于参数化查询的场景是优先的方案
 C. 转码是优选的SQL注入防护措施
 D. 在拼接SQL语句前进行转码，可以彻底解决SQL注入问题

你的回答B 是错误的。暂时不知道答案

**Comment by Feynming** [comment]
这题选A

**Comment by waylau** [comment]
@Feynming thx
