### ISSUE TITLE
Math.round(11.5) 等于多少 (). Math.round(-11.5) 等于多少 ( ).

### ISSUE THREAD

**Issue by waylau** [waylau/java-trusted-coding-exam#89]
Math.round(11.5) 等于多少 (). Math.round(-11.5) 等于多少 ( ).(2分)

 
A. 11 ,-11
B. 11 ,-12
C. 12 ,-11
D. 12 ,-12

你的回答
•	C

**Comment by Ricardo-anser** [comment]
解析：Math.round会把值向大的方向去取

**Comment by waylau** [comment]
round 表示"四舍五入"，算法为Math.floor(x+0.5) ，即将原来的数字加上 0.5 后再向下取整
